### ISSUE TITLE
Azure DevOps git repository not being recognized

### ISSUE THREAD

**Issue by fbussolin** [WoozyMasta/archimate-ci-image#11]
Hello,

My Azure DevOps git repository does not have .git extension in the url and seems like the archimate-ci-image script is enforcing it.

I cannot confirm if that is the issue but my point is:

- Is there any way to improve the validation (regex?) and recognize git urls like this
**https://company@dev.azure.com/company/architecture/_git/archi**

Note: Azure DevOps is generating url using this pattern.

**Comment by WoozyMasta** [comment]
@fbussolin 
Hi, I don't know anything about Azure DevOps, I don't have an account there, and I don't want to get involved with it either.

If someone can fix this, I'll gladly consider such a PR

**Comment by fbussolin** [comment]
Hi @WoozyMasta ,
Thank you for your prompt answer!
I do not think Azure DevOps is the point here, let's consider just a regular git repository and remove the Azure DevOps from the question.

So it will be: Can the current validation be improved to remove the need to have .git extension in the git repository?

Kind Regards,

**Comment by WoozyMasta** [comment]
@fbussolin 
Probably more information is needed, you can run the script in `bash -x` debug mode and show on which line the error occurs

Are you using ssh? What if we just use https and access token?

**Comment by WoozyMasta** [comment]
oh, sorry, I was in a hurry, I understand what you mean

[LL35C25-L35C32](https://github.com/WoozyMasta/archimate-ci-image/blob/b38830882aebe5af4b6b85865733aaffd939fff6/entrypoint.sh#LL35C25-L35C32) here should be made an optional .git checkout

and Azure swears if you add .git at the end?

**Comment by WoozyMasta** [comment]
@fbussolin try to use the code from this [try_fix_azure](https://github.com/WoozyMasta/archimate-ci-image/tree/try_fix_azure) branch, maybe it will be enough and let me know

**Comment by fbussolin** [comment]
Yes, I think that's correct what you pointed.
The url is being generated at company level and I do not have access to modify it.

Here is the console output for me:
![image](https://github.com/WoozyMasta/archimate-ci-image/assets/6156934/4790a595-a093-4e0c-a0a7-2afedf6e7a42)
