### ISSUE TITLE
Is the gh-pages branch orphaned from the master branch?

### ISSUE THREAD

**Issue by JmLallem** [WoozyMasta/archimate-ci-image#13]
Hi
Could you tell me if the gh-pages branch needs to be or not, orphaned from the master branch ?
Did you use "git checkout --orphan gh-pages" ?
Thank you so much for your help
Regards

**Comment by WoozyMasta** [comment]
@JmLallem, yes
 `gh-pages` is a service branch for storing a report (pdf, html files, etc.) and it is not related to the main branch by code

Just look at it as a separate directory for storing reports.
